version=2.1.2-SNAPSHOT

# The version of the MarkLogic Spark connector to be used by Flux.
connectorVersion=3.1.2-SNAPSHOT

picocliVersion=4.7.7

# Aligned with our Spark connector.
sparkVersion=4.2.0
hadoopVersion=3.5.0

# We want the minor version to match Spark, but the patch version can be higher. This is the case with 2.21.x, where
# LangChain4j is using 2.21.4 and Spark 4.2.0 is using 2.21.2, but 2.21.5 is available.
jacksonVersion=2.21.5

# This needs to match the version used by Hadoop.
awssdkVersion=2.35.4

nettyVersion=4.2.16.Final
langchain4jVersion=1.17.2
tikaVersion=3.3.1

# Define these on the command line to publish to OSSRH
# See https://central.sonatype.org/publish/publish-gradle/#credentials for more information
mavenCentralUsername=
mavenCentralPassword=
mavenCentralUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/

# For publishing to internal Nexus repository
publishUrl=file:../releases

# Adding these based on the non-standard JDK locations used by Jenkins.
# See https://docs.gradle.org/current/userguide/toolchains.html#sec:custom_loc for information
# on custom toolchain locations in Gradle.
org.gradle.java.installations.fromEnv=JAVA_HOME_DIR
org.gradle.java.installations.paths=/users/ml/builder/java/jdk-11.0.2,/home/builder/java/jdk-17.0.2

# Bumping this up as with Spark 4, Gradle often runs into heap space issues when trying to build the project.
org.gradle.jvmargs=-Xmx4g
